config/routes.rb
Blog::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'articles/new_comment/:id', to: 'articles#new_comment', as: 'new_comment'
  post 'articles/save/:id', to: 'articles#save', as: 'save'

  resources :users
  resources :sessions
  resources :posts

  root to: 'articles#index'
  resources :articles
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :course_code,:presence => true
  #~ validates :course_code, :length => {:maximum => 20}
  validates :name,:presence => true
  #~ validates :name, :length => {:maximum => 20}
  #validates :course_code, :uniqueness => {:message=>"Already a professor has been taken this course"}

  has_many :comments
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authorize, only: [:edit, :update]
  
  def index
    @articles = Article.all
    #~ 0 => Aerospace Engineering  
    #~ 1 => Applied Statistics and Informatics  
    #~ 2 => Biosciences & Bioengineering 
    #~ 3 => Chemical Engineering  
    #~ 4 => Chemistry  
    #~ 5 => Civil Engineering  
    #~ 6 => Computer Science and Engineering 
    #~ 7 => Earth Sciences
    #~ 8 => Electrical Engineering  
    #~ 9 => Energy Science and Engineering  
    #~ 10 => Engineering Physics  
    #~ 11 => Humanities and Social Sciences
    #~ 12 => Mathematics
    #~ 13 => Mechanical Engineering
    #~ 14 => Metallurgical Engineering and Materials Science  
    #~ 15 => Physics  
    #~ 16 => Centre for Entrepreneurship
    #~ 17 => Centre for Environmental Science & Engineering  
    #~ 18 => Centre for Research in Nano Technology and Sciences  
    #~ 19 => Centre for Technology Alternatives for Rural Areas  
    #~ 20 => Centre for Urban Science and Engineering  
    #~ 21 => Centre of Studies in Resources Engineering  
    #~ 22 => Animation  
    #~ 23 => Industrial Design Centre  
    #~ 24 => Interaction Design  
    #~ 25 => Mobility and Vehicle Design  
    #~ 26 => Visual Communication  
    #~ 27 => Climate Studies  
    #~ 28 => Educational Technology  
    #~ 29 => Industrial Engineering and Operations Research  
    #~ 30 => Systems and Control Engineering  
    #~ 31 => Shailesh J. Mehta School of Management  
    #~ 32 => Other 
    
    @dept_count=33
    @article_dept=Array.new(@dept_count){Array.new}
    @articles.each do |article|
		if article.course_code[0..1]=="AE"
			@article_dept[0].push(article)
		elsif article.course_code[0..1]=="SI"
			@article_dept[1].push(article)
		elsif article.course_code[0..1]=="BB" || article.course_code[0..1]=="BM" || article.course_code[0..1]=="BM" || article.course_code[0..1]=="BT"
			@article_dept[2].push(article)
		elsif article.course_code[0..1]=="CL"
			@article_dept[3].push(article)
		elsif article.course_code[0..1]=="CH"
			@article_dept[4].push(article)
		elsif article.course_code[0..1]=="CE"
			@article_dept[5].push(article)
		elsif article.course_code[0..1]=="CS"
			@article_dept[6].push(article)
		elsif article.course_code[0..1]=="GS"
			@article_dept[7].push(article)
		elsif article.course_code[0..1]=="EE"
			@article_dept[8].push(article)
		elsif article.course_code[0..1]=="EN"
			@article_dept[9].push(article)
		elsif article.course_code[0..1]=="EP"
			@article_dept[10].push(article)
		elsif article.course_code[0..1]=="HS"
			@article_dept[11].push(article)
		elsif article.course_code[0..1]=="MA"
			@article_dept[12].push(article)
		elsif article.course_code[0..1]=="ME"
			@article_dept[13].push(article)
		elsif article.course_code[0..1]=="MM"
			@article_dept[14].push(article)
		elsif article.course_code[0..1]=="PH"
			@article_dept[15].push(article)
		elsif article.course_code[0..1]==""    ##### No course code found for this.
			@article_dept[16].push(article)
		elsif article.course_code[0..1]=="ES"
			@article_dept[17].push(article)
		elsif article.course_code[0..1]=="NT"
			@article_dept[18].push(article)
		elsif article.course_code[0..1]=="TD"
			@article_dept[19].push(article)
		elsif article.course_code[0..1]==""   ##### No course code found for this.
			@article_dept[20].push(article)
		elsif article.course_code[0..1]=="NR" || article.course_code[0..2]=="GNR"
			@article_dept[21].push(article)
		elsif article.course_code[0..1]=="AN"
			@article_dept[22].push(article)
		elsif article.course_code[0..1]=="ID"
			@article_dept[23].push(article)
		elsif article.course_code[0..1]=="IN"
			@article_dept[24].push(article)
		elsif article.course_code[0..1]=="MD"
			@article_dept[25].push(article)
		elsif article.course_code[0..1]=="VC"
			@article_dept[26].push(article)
		elsif article.course_code[0..1]=="CM"
			@article_dept[27].push(article)
		elsif article.course_code[0..1]=="ET"
			@article_dept[28].push(article)
		elsif article.course_code[0..1]=="IE"
			@article_dept[29].push(article)
		elsif article.course_code[0..1]=="SC"
			@article_dept[30].push(article)
		elsif article.course_code[0..1]=="MG" || article.course_code[0..1]=="MN"
			@article_dept[31].push(article)
		else
			@article_dept[32].push(article)
		end
    end
    @users = User.all
  end

  def show
    @article = Article.find(params[:id])
    @user = User.find_by_email(@article.ind)	#ind will be equal to profe
    @posts = Post.all
    @post = Post.new
    @index_var=0;
  end
  
  def new
	@article = Article.new
  end
	
  def create
  	#@article = Article.new(params[:article])
	@article = Article.new(params[:article])  # VVVVIMP  =>  This params will get that post info that was sent by new html on submitting.
	#this returns a bool if it succeeds
	#~ @article.ind=current_user.email
	if @article.save
		redirect_to root_url, :notice=> "Course is added successfully"
	else 
		render "new"
	end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      redirect_to @article, notice: "Course info's modified content has been updated."
    else
      render "edit"
    end
  end
  
  def destroy
		@article = Article.find(params[:id])
		posts=Post.all
		posts.each do |post|
			if post.ind == @article.id.to_s then
				post.destroy
			end
		end
		@article.destroy
		redirect_to root_url, :notice => "Course successfully deleted!"
  end
  
  def new_comment
    @article = Article.find(params[:id])
    if @article
		@post=Post.new
		#~ @post = Post.new(params[:post])
		#~ @post.ind=params[:id]
		#~ @post.prof_student=current_user.prof_student
		#~ @post.name=current_user.name
		#~ @post.email=current_user.email 
		#~ @post.save
			#~ redirect_to root_url
	else
		redirect_to show_article_path(article)
	end
  end
  
  def save
    @article = Article.find(params[:id])
	@post = Post.new(params[:post])
	@post.ind=params[:id]
	@post.prof_student=current_user.prof_student
	@post.name=current_user.name
	@post.email=current_user.email 
	@post.save
	redirect_to :action => "show", :id => params[:id]
  end
  
  #~ private
	#~ 
	#~ def post_params
	#~ params.require(:post).permit(:title, :content)
	#~ end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<!DOCTYPE html>
<html ng-app="myApp" >
	<head>
		<title>Course Info</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<script>
			var app = angular.module('myApp', []);
			app.controller('myCtrl', function($scope) {
				$scope.items=[
					{value:'0', name:'Aerospace Engineering'},
					{value:'1', name:'Applied Statistics and Informatics'},
					{value:'2', name:'Biosciences & Bioengineering'},
					{value:'3', name:'Chemical Engineering'},			
					{value:'4', name:'Chemistry'},
					{value:'5', name:'Civil Engineering'},
					{value:'6', name:'Computer Science and Engineering'},
					{value:'7', name:'Earth Sciences'},
					{value:'8', name:'Electrical Engineering'},
					{value:'9', name:'Energy Science and Engineering'},
					{value:'10', name:'Engineering Physics'},
					{value:'11', name:'Humanities and Social Sciences'},
					{value:'12', name:'Mathematics'},
					{value:'13', name:'Mechanical Engineering'},
					{value:'14', name:'Metallurgical Engineering and Materials Science'},
					{value:'15', name:'Physics'},
					{value:'16', name:'Centre for Entrepreneurship'},
					{value:'17', name:'Centre for Environmental Science & Engineering'},
					{value:'18', name:'Centre for Research in Nano Technology and Sciences'},
					{value:'19', name:'Centre for Technology Alternatives for Rural Areas'},
					{value:'20', name:'Centre for Urban Science and Engineering'},
					{value:'21', name:'Centre of Studies in Resources Engineering'},
					{value:'22', name:'Animation'},
					{value:'23', name:'Industrial Design Centre'},
					{value:'24', name:'Interaction Design'},
					{value:'25', name:'Mobility and Vehicle Design'},
					{value:'26', name:'Visual Communication'},
					{value:'27', name:'Climate Studies'},
					{value:'28', name:'Educational Technology'},
					{value:'29', name:'Industrial Engineering and Operations Research'},
					{value:'30', name:'Systems and Control Engineering'},
					{value:'31', name:'Shailesh J. Mehta School of Management'},
					{value:'32', name:'Other Courses'}
				];
				$scope.form = {type:$scope.items[0]};
				$scope.equaliser = function(msgAuthor, currentUser) {
					return angular.equals(msgAuthor, currentUser);
				}
			});
		</script>
	</head>
	<body ng-controller="myCtrl">
		<nav class="navbar navbar-fixed-top" style="top:50px;background:#D8D8D8;height:70px;">
			<br>
			<div class="container">
				<div class="nav navbar-nav">
					<h4> <b> Course Information at IIT BOMBAY </b> </h4>
				</div>
				<div class="nav navbar-nav navbar-right">
					<%if current_user%>
						<% if current_user.email == "kranthi@gmail.com" ||  current_user.email == "kiranking@gmail.com"%>
							<%= link_to "Add a new course", new_article_path, :class=>'btn btn-success', :role=>'button'%>
						<%end%>
						<% if current_user.prof_student == "Faculty" || current_user.email == "kranthi@gmail.com" ||  current_user.email == "kiranking@gmail.com" %>
							<%= link_to "Add Teaching Course", edit_user_path(current_user), :class=>'btn btn-primary', :role=>'button', :title=>'select the course that is being taight by you'%>
						<%end%>
					<%end%>
				</div>
			</div>
		</nav>
		<div class="container" style="padding-top:75px;">
			<% if current_user %>
				<div class="form-group">
					<label for="select_fac" class="col-sm-2 control-label">Choose Department</label>
					<div class="col-sm-10">
						<select ng-model="form.type" required ng-options="item.name for item in items" class="form-control options"></select>
					</div>
				</div><br/><br/>
				<div class="well">
					<table class = "table table-hover table-striped" id="regions">
						<thead>
							<tr>
								<th>Sr No.</th>
								<th>Course Code</th>
								<th>Course Name</th>
								<th>View more</th>
								<% if current_user.email == "kranthi@gmail.com" ||  current_user.email == "kiranking@gmail.com"%>
									<th>Edit</th>
									<th>Delete</th>
								<%end%>
							</tr>
						</thead>
						<%for i in 0..@dept_count-1%> 
							<tbody ng-if="equaliser(form.type.value,'<%=i%>')">
								<%sr_no=1%>
								<% @article_dept[i].each do |article| %>
									<tr>
										<td>
											<%=sr_no%>
										</td>
										<td>
											<%= article.course_code %> <br/>
										</td>
										<td>
											<%=article.name%>
										</td>
										<td>
											<%=link_to "More Info", article, :class=>'btn btn-success', :role=>'button'%>
										</td>
										<% if current_user.email == "kranthi@gmail.com" ||  current_user.email == "kiranking@gmail.com"%>
											<td>
												<%=link_to "Edit", edit_article_path(article), :class=>'btn btn-warning', :role=>'button'%>
											</td>
											<td>
												<%=link_to 'Delete', article, :method=> :delete, data: { confirm: 'Are you sure you want to delete this Course?'}, :class=>'btn btn-danger', :role=>'button'%>
											</td>
										<%end%>
									</tr>
									<%sr_no=sr_no+1%>
								<%end%>
							</tbody>
						<%end%>
					</table>
				</div>
			<% else %>
				<p>Kindly login using your ids in order to see the information about courses. Sign Up if you had never registered.</p>
			<%end%>
		</div>
		<script src= "http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>
	</body>
</html>

app/views/articles/new.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Course Info</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
	</head>
	<body>
		<nav class="navbar navbar-fixed-top" style="top:50px;background:#D8D8D8;height:70px;">
			<br>
			<div class="container">
				<div class="nav navbar-nav">
					<h4> <b> Adding a new course</b> </h4>
				</div>
			</div>
		</nav>
		
		<div class="container" style="padding-top:75px;">
			<%= form_for @article, :class=>'form-horizontal' do |var_form| %>
				<% if @article.errors.any? %>
					<h2>Errors</h2>
					<ul>
						<% @article.errors.full_messages.each do |message| %>
							<li><%= message %></li>
						<% end %>
					</ul>
				<%end%>
				<div class="form-group">
					<%= var_form.label :course_code, "Course Code", :for=>"course_code", :class=>"col-sm-2 control-label"%> 
					<div class="col-sm-10">
						<%= var_form.text_field :course_code, :class=>"form-control", :id=>"course_code", :placeholder=>"CS 101"%> <br/>
					</div>
				</div>
				<div class="form-group">
					<%= var_form.label :name, "Course Name", :for=>"name", :class=>"col-sm-2 control-label"%> 
					<div class="col-sm-10">
						<%= var_form.text_field :name, :class=>"form-control", :id=>"name", :placeholder=>"Computer Programming and Utilization"%> <br/>
					</div>
				</div>
				<div class="form-group">
					<%= var_form.label :org_total_credits, "Total Credits", :for=>"org_total_credits", :class=>"col-sm-2 control-label"%> 
					<div class="col-sm-10">
						<%= var_form.text_field :org_total_credits, :class=>"form-control", :id=>"org_total_credits", :placeholder=>"6"%> <br/>
					</div>
				</div>
				<div class="form-group">
					<%= var_form.label :org_type, "Course Type", :for=>"org_type", :class=>"col-sm-2 control-label"%> 
					<div class="col-sm-10">
						<%= var_form.text_field :org_type, :class=>"form-control", :id=>"org_type", :placeholder=>"T"%> <br/>
					</div>
				</div>
				<div class="form-group">
					<%= var_form.label :org_lecture_credits, "Lecture Credits", :for=>"org_lecture_credits", :class=>"col-sm-2 control-label"%> 
					<div class="col-sm-10">
						<%= var_form.text_field :org_lecture_credits, :class=>"form-control", :id=>"org_lecture_credits", :placeholder=>"6"%> <br/>
					</div>
				</div>
				<div class="form-group">
					<%= var_form.label :org_tutorial, "Tutorial Credits", :for=>"org_tutorial", :class=>"col-sm-2 control-label"%> 
					<div class="col-sm-10">
						<%= var_form.text_field :org_tutorial, :class=>"form-control", :id=>"org_tutorial", :placeholder=>"2"%> <br/>
					</div>
				</div>
				<div class="form-group">
					<%= var_form.label :org_practical, "Practice Credits", :for=>"org_practical", :class=>"col-sm-2 control-label"%> 
					<div class="col-sm-10">
						<%= var_form.text_field :org_practical, :class=>"form-control", :id=>"org_practical", :placeholder=>"0"%> <br/>
					</div>
				</div>
				<div class="form-group">
					<%= var_form.label :org_self_study, "Self study Credits", :for=>"org_self_study", :class=>"col-sm-2 control-label"%> 
					<div class="col-sm-10">
						<%= var_form.text_field :org_self_study, :class=>"form-control", :id=>"org_self_study", :placeholder=>"0"%> <br/>
					</div>
				</div>
				<div class="form-group">
					<%= var_form.label :org_half_semester, "Half Semester(Y or N)", :for=>"org_half_semester", :class=>"col-sm-2 control-label"%> 
					<div class="col-sm-10">
						<%= var_form.text_field :org_half_semester, :class=>"form-control", :id=>"org_half_semester", :placeholder=>"N"%> <br/>
					</div>
				</div>
				<div class="form-group">
					<%= var_form.label :org_prerequisite, "Prerequisite(s)", :for=>"org_prerequisite", :class=>"col-sm-2 control-label"%> 
					<div class="col-sm-10">
						<%= var_form.text_field :org_prerequisite, :class=>"form-control", :id=>"org_prerequisite", :placeholder=>"Nil"%> <br/>
					</div>
				</div>
				<div class="form-group">
					<%= var_form.label :org_text_reference, "Text References", :for=>"org_text_reference", :class=>"col-sm-2 control-label"%> 
					<div class="col-sm-10">
						<%= var_form.text_area :org_text_reference, :class=>"form-control", :rows=>"5", :id=>"org_text_reference", :placeholder=>"Text References"%> <br/>
					</div>
				</div>
				<div class="form-group">
					<%= var_form.label :org_content, "Course Content", :for=>"org_content", :class=>"col-sm-2 control-label"%> 
					<div class="col-sm-10">
						<%= var_form.text_area :org_content, :class=>"form-control", :rows=>"5", :id=>"org_content", :placeholder=>"Course Content"%> <br/>
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-10">
						<%= var_form.submit "CONFIRM", :class=>"btn btn-success"%> <br/> <br/>
						<%= link_to "Go back to Courses", root_url, :class=>"btn btn-danger", :role=>"button" %><br/><br/><br/>
					</div>
				</div>
			<% end %>
		</div>
	</body>
</html>

app/views/articles/new_comment.html.erb
<h1>Adding comment</h1>

<%= form_for  @post, :url => {:action => "save"} do |f| %>
  <% if @post.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
	<%= f.label :comment %><br />
	<%= f.text_area :comment %>
	</div>
	<div class="actions"><%= f.submit "Add Comment" %></div>
<% end %>

app/views/articles/show.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Course Info</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<style>
			.detailBox {
				width:100%;
				border:1px solid #bbb;
			}
			.titleBox {
				background-color:#fdfdfd;
				padding:10px;
			}
			.titleBox label{
			  color:#444;
			  margin:0;
			  display:inline-block;
			}
			
			.commentBox {
				padding:10px;
				border-top:1px dotted #bbb;
			}
			.commentBox .form-group:first-child, .actionBox .form-group:first-child {
				width:80%;
			}
			.commentBox .form-group:nth-child(2), .actionBox .form-group:nth-child(2) {
				width:18%;
			}
			.taskDescription {
				margin-top:10px 0;
			}
			.commentList {
				padding:0;
				list-style:none;
				overflow:auto;
			}
			.commentList li {
				margin:0;
				margin-top:10px;
			}
			.commentList li > div {
				display:table-cell;
			}
			.commentText p {
				margin:0;
			}
			ul{
				list-style-type: none;
			}
			.sub-text {
				color:#aaa;
				font-family:verdana;
				font-size:13px;
			}
			.actionBox {
				border-top:1px dotted #bbb;
				padding:10px;
			}
		</style>
	</head>
	<body>
		<nav class="navbar navbar-fixed-top" style="top:50px;background:#D8D8D8;height:70px;">
			<br>
			<div class="container">
				<div class="nav navbar-nav">
					<h4> <b> Course Information of <%=@article.course_code%>(<%=@article.name%>)</b> </h4>
				</div>
				<div class="nav navbar-nav navbar-right">
					<%if current_user%>
						<% if current_user.email == "kranthi@gmail.com" ||  current_user.email == "kiranking@gmail.com"%>
							<%= link_to "Add a new course", new_article_path, :class=>'btn btn-success', :role=>'button'%>
						<%end%>
						<% if current_user.prof_student == "Faculty" || current_user.email == "kranthi@gmail.com" ||  current_user.email == "kiranking@gmail.com" %>
							<%= link_to "Add Teaching Course", edit_user_path(current_user), :class=>'btn btn-primary', :role=>'button', :title=>'select the course that is being taight by you'%>
						<%end%>
					<%end%>
				</div>
			</div>
		</nav>
		<div class="container" style="padding-top:75px;">
			<%if @user%>
				<div class="info">
					<p> Instructor's Name: <%=@user.name%> </p>
					<p> Instructor's email: <%=@user.email%> </p>
				</div>
			<%end%>
			<table class = "table table-bordered" id="regions">
				<thead>
					<tr>
						<th>Fields</th>
					    <th>Original Content</th>		
					    <th>Modified Content</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td style="width:20%">Course Code</td>
						<td style="width:40%"><%=@article.course_code%></td>		
						<td style="width:40%"><%=@article.course_code%></td>
					</tr>
					<tr>
						<td>Course Name</td>
						<td><%=@article.name%></td>		
						<td><%=@article.name%></td>
					</tr>
					<tr>
						<td>Total Credits</td>
						<td><%=@article.org_total_credits%></td>		
						<td><%=@article.mod_total_credits%></td>
					</tr>
					<tr>
						<td>Type</td>
						<td><%=@article.org_type%></td>		
						<td><%=@article.mod_type%></td>
					</tr>
					<tr>
						<td>Lecture</td>
						<td><%=@article.org_lecture_credits%></td>		
						<td><%=@article.mod_lecture_credits%></td>
					</tr>
					<tr>
						<td>Tutorial</td>
						<td><%=@article.org_tutorial%></td>		
						<td><%=@article.mod_tutorial%></td>
					</tr>
					<tr>
						<td>Practical</td>
						<td><%=@article.org_practical%></td>		
						<td><%=@article.mod_practical%></td>
					</tr>
					<tr>
						<td>Self study</td>
						<td><%=@article.org_self_study%></td>		
						<td><%=@article.mod_self_study%></td>
					</tr>
					<tr>
						<td>Half Semester</td>
						<td><%=@article.org_half_semester%></td>		
						<td><%=@article.mod_half_semester%></td>
					</tr>
					<tr>
						<td>Prerequisite</td>
						<td><%=@article.org_prerequisite%></td>		
						<td><%=@article.mod_prerequisite%></td>
					</tr>
					<tr>
						<td>Text Reference</td>
						<td><%=@article.org_text_reference%></td>		
						<td><%=@article.mod_text_reference%></td>
					</tr>
					<tr>
						<td>Description</td>
						<td><%=@article.org_content%></td>		
						<td><%=@article.mod_content%></td>
					</tr>
				</tbody>
			</table>
		</div>
	<%if current_user%>
		<%if (current_user.prof_student=="Faculty" && current_user.email==@article.ind) || current_user.email == "kranthi@gmail.com" ||  current_user.email == "kiranking@gmail.com"%> 
			<%=link_to "Edit Modified Content", edit_article_path(@article), :class=>'btn btn-success', :role=>'button', :style=>""%></br></br>
		<%end%>
	<%end%>



<!--
*************************************************************************************************
-->




<div class="detailBox">
    <div class="titleBox">
      <label>Comment Box</label>
        <button type="button" class="close" aria-hidden="true">&times;</button>
    </div>
    <div class="commentBox">
        <p class="taskDescription">This is a discussion box where students can comment on the courses and their description and Instructors could reply to them.</p>
    </div>
    <div class="actionBox">
        <ul class="commentList">
			<% @posts.each do |post| %>
				<%if post.ind == @article.id.to_s %>
					<li>
						<div class="commentText">
							<p style="color:blue;"><%=post.name%>(<%=post.email%>) <%if post.email==@article.ind%> (instructor)<%end%></p>
							<p class=""><%=post.comment%></p> <span class="date sub-text"><%="#{time_ago_in_words(post.created_at)} ago"%></span><br/>
							<%if current_user.email == "kiranking@gmail.com" %> 
								<%=link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure you want to delete this post?'},:class=>'btn btn-danger', :role=>'button'%>
							<%end%>
						</div>
					</li>
					<hr/>
				<%end%>
			<%end%>
        </ul>
    </div>
</div>
<br/>
<%= form_for  @post, :url => {:action => "save"}, :class=>'form-inline' do |f| %>
	<% if @post.errors.any? %>
		<div class="error_messages">
			<h2>Comment is invalid</h2>
			<ul>
				<% @post.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="form-group">
		<%= f.text_area :comment, :rows=>"3", :class=>"form-control", :placeholder=>"add comment"%>
	</div>
	<%= f.submit "Add my comment", :class=>"btn btn-success"%> <br/> <br/>
<%end%>
<br/>
<br/>

</body>
</html>